function [f_full_abs] = f_full_abs(x,u,p)

  f_full_abs(1,1)=x(3);
  f_full_abs(2,1)=x(4);
  f_full_abs(3,1)=(p.a_len^2*p.m_leg*u + p.l^2*p.m_leg*u + p.l^2*p.mh*u - (p.b_len^2*p.l^2*...
         p.m_leg^2*x(3)^2*sin(2*x(1) - 2*x(2)))/2 - p.b_len*p.l*p.m_leg*u*cos(x(1) - x(2)) + p.b_len*p.l^3*p.m_leg^2*...
         x(4)^2*sin(x(1) - x(2)) - p.a_len^2*p.b_len*p.g0*p.m_leg^2*sin(x(1)) - p.b_len*p.g0*p.l^2*p.m_leg^2*...
         sin(x(1)) + p.b_len*p.l^3*p.m_leg*p.mh*x(4)^2*sin(x(1) - x(2)) + p.a_len^2*p.b_len*p.l*p.m_leg^2*x(4)^2*...
         sin(x(1) - x(2)) - p.b_len*p.g0*p.l^2*p.m_leg*p.mh*sin(x(1)) + p.b_len*p.g0*p.l^2*p.m_leg^2*cos(x(1) - x(2))*...
         sin(x(2)) + p.a_len*p.b_len*p.g0*p.l*p.m_leg^2*cos(x(1) - x(2))*sin(x(2)) + p.b_len*p.g0*p.l^2*p.m_leg*p.mh*...
         cos(x(1) - x(2))*sin(x(2)))/(p.b_len^2*p.m_leg*(p.a_len^2*p.m_leg + p.l^2*p.m_leg + p.l^2*p.mh - p.l^2*...
         p.m_leg*cos(x(1) - x(2))^2));
  f_full_abs(4,1)=(2*p.l*u*cos(x(1) - x(2)) - 2*p.b_len*u + p.b_len*p.l^2*p.m_leg*x(4)^2*sin(2*...
         x(1) - 2*x(2)) - p.b_len*p.g0*p.l*p.m_leg*sin(2*x(1) - x(2)) + 2*p.a_len*p.b_len*p.g0*p.m_leg*sin(x(2)) +...
          p.b_len*p.g0*p.l*p.m_leg*sin(x(2)) + 2*p.b_len*p.g0*p.l*p.mh*sin(x(2)) - 2*p.b_len^2*p.l*p.m_leg*x(3)^2*...
         sin(x(1) - x(2)))/(2*p.b_len*(p.a_len^2*p.m_leg + p.l^2*p.m_leg + p.l^2*p.mh - p.l^2*p.m_leg*cos(x(1) - x(2))^2));

 