function [input_PD_FL_abs_full_f] = input_PD_FL_abs_full_f(x,p)

  input_PD_FL_abs_full_f(1,1)=-(p.D_gain*(x(3) + x(4)*((5*p.A_vec(1)*(p.phaseInit -...
          x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (5*p.A_vec(2)*(p.phaseInit - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 + (5*...
         p.A_vec(5)*(p.phaseFinal - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (5*p.A_vec(6)*(p.phaseFinal -...
          x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (20*p.A_vec(2)*(p.phaseInit - x(2))^3*(p.phaseFinal - x(2)))/(p.phaseInit -...
          p.phaseFinal)^5 - (20*p.A_vec(4)*(p.phaseInit - x(2))*(p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (20*...
         p.A_vec(5)*(p.phaseInit - x(2))*(p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (10*p.A_vec(3)*(2*...
         p.phaseFinal - 2*x(2))*(p.phaseInit - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (30*p.A_vec(3)*(p.phaseInit -...
          x(2))^2*(p.phaseFinal - x(2))^2)/(p.phaseInit - p.phaseFinal)^5 - (30*p.A_vec(4)*(p.phaseInit - x(2))^2*...
         (p.phaseFinal - x(2))^2)/(p.phaseInit - p.phaseFinal)^5)) + p.P_gain*(x(1) - (p.A_vec(1)*(p.phaseInit -...
          x(2))^5)/(p.phaseInit - p.phaseFinal)^5 + (p.A_vec(6)*(p.phaseFinal - x(2))^5)/(p.phaseInit - p.phaseFinal)^5 + (5*...
         p.A_vec(2)*(p.phaseInit - x(2))^4*(p.phaseFinal - x(2)))/(p.phaseInit - p.phaseFinal)^5 - (5*p.A_vec(5)*...
         (p.phaseInit - x(2))*(p.phaseFinal - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (10*p.A_vec(3)*(p.phaseInit -...
          x(2))^3*(p.phaseFinal - x(2))^2)/(p.phaseInit - p.phaseFinal)^5 + (10*p.A_vec(4)*(p.phaseInit - x(2))^2*...
         (p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5) - (20*x(4)^2*(p.A_vec(1)*p.phaseInit^3 - 2*p.A_vec(2)*...
         p.phaseInit^3 + p.A_vec(3)*p.phaseInit^3 - p.A_vec(4)*p.phaseFinal^3 + 2*p.A_vec(5)*p.phaseFinal^3 - p.A_vec(6)*...
         p.phaseFinal^3 - p.A_vec(1)*x(2)^3 + 5*p.A_vec(2)*x(2)^3 - 10*p.A_vec(3)*x(2)^3 + 10*p.A_vec(4)*x(2)^3 - 5*...
         p.A_vec(5)*x(2)^3 + p.A_vec(6)*x(2)^3 - 3*p.A_vec(2)*p.phaseInit^2*p.phaseFinal + 3*p.A_vec(3)*p.phaseInit*...
         p.phaseFinal^2 + 6*p.A_vec(3)*p.phaseInit^2*p.phaseFinal - 6*p.A_vec(4)*p.phaseInit*p.phaseFinal^2 - 3*p.A_vec(4)*...
         p.phaseInit^2*p.phaseFinal + 3*p.A_vec(5)*p.phaseInit*p.phaseFinal^2 + 3*p.A_vec(1)*p.phaseInit*x(2)^2 - 3*...
         p.A_vec(1)*p.phaseInit^2*x(2) - 12*p.A_vec(2)*p.phaseInit*x(2)^2 + 9*p.A_vec(2)*p.phaseInit^2*x(2) + 18*...
         p.A_vec(3)*p.phaseInit*x(2)^2 - 9*p.A_vec(3)*p.phaseInit^2*x(2) - 12*p.A_vec(4)*p.phaseInit*x(2)^2 + 3*...
         p.A_vec(4)*p.phaseInit^2*x(2) + 3*p.A_vec(5)*p.phaseInit*x(2)^2 - 3*p.A_vec(2)*p.phaseFinal*x(2)^2 + 12*...
         p.A_vec(3)*p.phaseFinal*x(2)^2 - 3*p.A_vec(3)*p.phaseFinal^2*x(2) - 18*p.A_vec(4)*p.phaseFinal*x(2)^2 + 9*...
         p.A_vec(4)*p.phaseFinal^2*x(2) + 12*p.A_vec(5)*p.phaseFinal*x(2)^2 - 9*p.A_vec(5)*p.phaseFinal^2*x(2) - 3*...
         p.A_vec(6)*p.phaseFinal*x(2)^2 + 3*p.A_vec(6)*p.phaseFinal^2*x(2) + 6*p.A_vec(2)*p.phaseInit*p.phaseFinal*...
         x(2) - 18*p.A_vec(3)*p.phaseInit*p.phaseFinal*x(2) + 18*p.A_vec(4)*p.phaseInit*p.phaseFinal*x(2) - 6*...
         p.A_vec(5)*p.phaseInit*p.phaseFinal*x(2)))/(p.phaseInit - p.phaseFinal)^5 - (2*p.a_len^2*p.g0*p.m_leg*...
         sin(x(1) - 2*x(2)) + p.a_len^2*p.g0*p.mh*sin(x(1) - 2*x(2)) + p.b_len^2*p.g0*p.m_leg*sin(x(1) - 2*x(2)) +...
          p.b_len^2*p.g0*p.mh*sin(x(1) - 2*x(2)) - 4*p.a_len^3*p.m_leg*x(4)^2*sin(x(1) - x(2)) - 2*p.a_len^3*p.mh*...
         x(4)^2*sin(x(1) - x(2)) - 2*p.b_len^3*p.m_leg*x(4)^2*sin(x(1) - x(2)) - 2*p.b_len^3*p.mh*x(4)^2*sin(x(1) -...
          x(2)) + 2*p.a_len^2*p.g0*p.m_leg*sin(x(1)) + p.a_len^2*p.g0*p.mh*sin(x(1)) + p.b_len^2*p.g0*p.m_leg*...
         sin(x(1)) + p.b_len^2*p.g0*p.mh*sin(x(1)) + p.b_len^3*p.m_leg*x(3)^2*sin(2*x(1) - 2*x(2)) + 3*p.a_len*p.b_len*...
         p.g0*p.m_leg*sin(x(1) - 2*x(2)) + 2*p.a_len*p.b_len*p.g0*p.mh*sin(x(1) - 2*x(2)) + 2*p.a_len*p.b_len^2*...
         p.m_leg*x(3)^2*sin(2*x(1) - 2*x(2)) + p.a_len^2*p.b_len*p.m_leg*x(3)^2*sin(2*x(1) - 2*x(2)) + p.a_len*...
         p.b_len*p.g0*p.m_leg*sin(x(1)) + 2*p.a_len*p.b_len*p.g0*p.mh*sin(x(1)) - 6*p.a_len*p.b_len^2*p.m_leg*x(4)^2*...
         sin(x(1) - x(2)) - 8*p.a_len^2*p.b_len*p.m_leg*x(4)^2*sin(x(1) - x(2)) - 6*p.a_len*p.b_len^2*p.mh*x(4)^2*...
         sin(x(1) - x(2)) - 6*p.a_len^2*p.b_len*p.mh*x(4)^2*sin(x(1) - x(2)))/(p.b_len*(3*p.a_len^2*p.m_leg + 2*...
         p.a_len^2*p.mh + p.b_len^2*p.m_leg + 2*p.b_len^2*p.mh - p.b_len^2*p.m_leg*cos(2*x(1) - 2*x(2)) + 2*p.a_len*...
         p.b_len*p.m_leg + 4*p.a_len*p.b_len*p.mh - p.a_len^2*p.m_leg*cos(2*x(1) - 2*x(2)) - 2*p.a_len*p.b_len*...
         p.m_leg*cos(2*x(1) - 2*x(2)))) + (((5*p.A_vec(1)*(p.phaseInit - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 -...
          (5*p.A_vec(2)*(p.phaseInit - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 + (5*p.A_vec(5)*(p.phaseFinal -...
          x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (5*p.A_vec(6)*(p.phaseFinal - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (20*...
         p.A_vec(2)*(p.phaseInit - x(2))^3*(p.phaseFinal - x(2)))/(p.phaseInit - p.phaseFinal)^5 - (20*p.A_vec(4)*...
         (p.phaseInit - x(2))*(p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (20*p.A_vec(5)*(p.phaseInit -...
          x(2))*(p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (10*p.A_vec(3)*(2*p.phaseFinal - 2*x(2))*...
         (p.phaseInit - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (30*p.A_vec(3)*(p.phaseInit - x(2))^2*(p.phaseFinal -...
          x(2))^2)/(p.phaseInit - p.phaseFinal)^5 - (30*p.A_vec(4)*(p.phaseInit - x(2))^2*(p.phaseFinal - x(2))^2)/(p.phaseInit -...
          p.phaseFinal)^5)*(3*p.a_len*p.g0*p.m_leg*sin(x(2)) - p.b_len*p.g0*p.m_leg*sin(2*x(1) - x(2)) - p.a_len*p.g0*p.m_leg*...
         sin(2*x(1) - x(2)) + 2*p.a_len*p.g0*p.mh*sin(x(2)) + p.b_len*p.g0*p.m_leg*sin(x(2)) + 2*p.b_len*p.g0*p.mh*...
         sin(x(2)) - 2*p.b_len^2*p.m_leg*x(3)^2*sin(x(1) - x(2)) + p.a_len^2*p.m_leg*x(4)^2*sin(2*x(1) - 2*x(2)) +...
          p.b_len^2*p.m_leg*x(4)^2*sin(2*x(1) - 2*x(2)) - 2*p.a_len*p.b_len*p.m_leg*x(3)^2*sin(x(1) - x(2)) + 2*p.a_len*...
         p.b_len*p.m_leg*x(4)^2*sin(2*x(1) - 2*x(2))))/(3*p.a_len^2*p.m_leg + 2*p.a_len^2*p.mh + p.b_len^2*p.m_leg +...
          2*p.b_len^2*p.mh - p.b_len^2*p.m_leg*cos(2*x(1) - 2*x(2)) + 2*p.a_len*p.b_len*p.m_leg + 4*p.a_len*...
         p.b_len*p.mh - p.a_len^2*p.m_leg*cos(2*x(1) - 2*x(2)) - 2*p.a_len*p.b_len*p.m_leg*cos(2*x(1) - 2*...
         x(2))))/((2*p.a_len^2*p.m_leg + p.a_len^2*p.mh + p.b_len^2*p.m_leg + p.b_len^2*p.mh + 2*p.a_len*p.b_len*...
         p.m_leg + 2*p.a_len*p.b_len*p.mh - p.b_len^2*p.m_leg*cos(x(1) - x(2)) - p.a_len*p.b_len*p.m_leg*cos(x(1) -...
          x(2)))/(p.b_len^2*p.m_leg*(2*p.a_len^2*p.m_leg + p.a_len^2*p.mh + p.b_len^2*p.m_leg + p.b_len^2*p.mh - p.b_len^2*...
         p.m_leg*cos(x(1) - x(2))^2 + 2*p.a_len*p.b_len*p.m_leg + 2*p.a_len*p.b_len*p.mh - p.a_len^2*p.m_leg*...
         cos(x(1) - x(2))^2 - 2*p.a_len*p.b_len*p.m_leg*cos(x(1) - x(2))^2)) + ((p.a_len*cos(x(1) - x(2)) - p.b_len +...
          p.b_len*cos(x(1) - x(2)))*((5*p.A_vec(1)*(p.phaseInit - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (5*...
         p.A_vec(2)*(p.phaseInit - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 + (5*p.A_vec(5)*(p.phaseFinal -...
          x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (5*p.A_vec(6)*(p.phaseFinal - x(2))^4)/(p.phaseInit - p.phaseFinal)^5 - (20*...
         p.A_vec(2)*(p.phaseInit - x(2))^3*(p.phaseFinal - x(2)))/(p.phaseInit - p.phaseFinal)^5 - (20*p.A_vec(4)*...
         (p.phaseInit - x(2))*(p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (20*p.A_vec(5)*(p.phaseInit -...
          x(2))*(p.phaseFinal - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (10*p.A_vec(3)*(2*p.phaseFinal - 2*x(2))*...
         (p.phaseInit - x(2))^3)/(p.phaseInit - p.phaseFinal)^5 + (30*p.A_vec(3)*(p.phaseInit - x(2))^2*(p.phaseFinal -...
          x(2))^2)/(p.phaseInit - p.phaseFinal)^5 - (30*p.A_vec(4)*(p.phaseInit - x(2))^2*(p.phaseFinal - x(2))^2)/(p.phaseInit -...
          p.phaseFinal)^5))/(p.b_len*(2*p.a_len^2*p.m_leg + p.a_len^2*p.mh + p.b_len^2*p.m_leg + p.b_len^2*p.mh - p.b_len^2*p.m_leg*...
         cos(x(1) - x(2))^2 + 2*p.a_len*p.b_len*p.m_leg + 2*p.a_len*p.b_len*p.mh - p.a_len^2*p.m_leg*cos(x(1) -...
          x(2))^2 - 2*p.a_len*p.b_len*p.m_leg*cos(x(1) - x(2))^2)));

 